/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardPreventiviRouteImport } from './routes/dashboard.preventivi'
import { Route as DashboardImpostazioniRouteImport } from './routes/dashboard.impostazioni'
import { Route as DashboardClientiRouteImport } from './routes/dashboard.clienti'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreventiviRoute = DashboardPreventiviRouteImport.update({
  id: '/preventivi',
  path: '/preventivi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpostazioniRoute = DashboardImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientiRoute = DashboardClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/dashboard/clienti'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard/clienti'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/dashboard/clienti'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preventivi': {
      id: '/dashboard/preventivi'
      path: '/preventivi'
      fullPath: '/dashboard/preventivi'
      preLoaderRoute: typeof DashboardPreventiviRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impostazioni': {
      id: '/dashboard/impostazioni'
      path: '/impostazioni'
      fullPath: '/dashboard/impostazioni'
      preLoaderRoute: typeof DashboardImpostazioniRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clienti': {
      id: '/dashboard/clienti'
      path: '/clienti'
      fullPath: '/dashboard/clienti'
      preLoaderRoute: typeof DashboardClientiRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientiRoute: typeof DashboardClientiRoute
  DashboardImpostazioniRoute: typeof DashboardImpostazioniRoute
  DashboardPreventiviRoute: typeof DashboardPreventiviRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientiRoute: DashboardClientiRoute,
  DashboardImpostazioniRoute: DashboardImpostazioniRoute,
  DashboardPreventiviRoute: DashboardPreventiviRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
