/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeSuccessRouteImport } from './routes/subscribe-success'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardPreventiviRouteImport } from './routes/dashboard.preventivi'
import { Route as DashboardImpostazioniRouteImport } from './routes/dashboard.impostazioni'
import { Route as DashboardFornitoriRouteImport } from './routes/dashboard.fornitori'
import { Route as DashboardClientiRouteImport } from './routes/dashboard.clienti'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardFattureRouteImport } from './routes/dashboard.fatture'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'

const SubscribeSuccessRoute = SubscribeSuccessRouteImport.update({
  id: '/subscribe-success',
  path: '/subscribe-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreventiviRoute = DashboardPreventiviRouteImport.update({
  id: '/preventivi',
  path: '/preventivi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpostazioniRoute = DashboardImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFornitoriRoute = DashboardFornitoriRouteImport.update({
  id: '/fornitori',
  path: '/fornitori',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientiRoute = DashboardClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFattureRoute = DashboardFattureRouteImport.update({
  id: '/fatture',
  path: '/fatture',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/fatture': typeof DashboardFattureRoute
  '/dashboard/fornitori': typeof DashboardFornitoriRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/fatture': typeof DashboardFattureRoute
  '/dashboard/fornitori': typeof DashboardFornitoriRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/subscribe-success': typeof SubscribeSuccessRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clienti': typeof DashboardClientiRoute
  '/dashboard/fatture': typeof DashboardFattureRoute
  '/dashboard/fornitori': typeof DashboardFornitoriRoute
  '/dashboard/impostazioni': typeof DashboardImpostazioniRoute
  '/dashboard/preventivi': typeof DashboardPreventiviRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/subscribe-success'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/clienti'
    | '/dashboard/fatture'
    | '/dashboard/fornitori'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscribe-success'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/clienti'
    | '/dashboard/fatture'
    | '/dashboard/fornitori'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/subscribe-success'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/clienti'
    | '/dashboard/fatture'
    | '/dashboard/fornitori'
    | '/dashboard/impostazioni'
    | '/dashboard/preventivi'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SubscribeSuccessRoute: typeof SubscribeSuccessRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe-success': {
      id: '/subscribe-success'
      path: '/subscribe-success'
      fullPath: '/subscribe-success'
      preLoaderRoute: typeof SubscribeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preventivi': {
      id: '/dashboard/preventivi'
      path: '/preventivi'
      fullPath: '/dashboard/preventivi'
      preLoaderRoute: typeof DashboardPreventiviRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impostazioni': {
      id: '/dashboard/impostazioni'
      path: '/impostazioni'
      fullPath: '/dashboard/impostazioni'
      preLoaderRoute: typeof DashboardImpostazioniRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fornitori': {
      id: '/dashboard/fornitori'
      path: '/fornitori'
      fullPath: '/dashboard/fornitori'
      preLoaderRoute: typeof DashboardFornitoriRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clienti': {
      id: '/dashboard/clienti'
      path: '/clienti'
      fullPath: '/dashboard/clienti'
      preLoaderRoute: typeof DashboardClientiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fatture': {
      id: '/dashboard/fatture'
      path: '/fatture'
      fullPath: '/dashboard/fatture'
      preLoaderRoute: typeof DashboardFattureRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardClientiRoute: typeof DashboardClientiRoute
  DashboardFattureRoute: typeof DashboardFattureRoute
  DashboardFornitoriRoute: typeof DashboardFornitoriRoute
  DashboardImpostazioniRoute: typeof DashboardImpostazioniRoute
  DashboardPreventiviRoute: typeof DashboardPreventiviRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardClientiRoute: DashboardClientiRoute,
  DashboardFattureRoute: DashboardFattureRoute,
  DashboardFornitoriRoute: DashboardFornitoriRoute,
  DashboardImpostazioniRoute: DashboardImpostazioniRoute,
  DashboardPreventiviRoute: DashboardPreventiviRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SubscribeSuccessRoute: SubscribeSuccessRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
