ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS cap TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS citta TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS provincia TEXT NOT NULL DEFAULT '';
